import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        // Legacy tokens (wizard/dashboard)
        brand: {
          50:  '#f0fdf4',
          100: '#dcfce7',
          400: '#4ade80',
          500: '#22c55e',
          600: '#16a34a',
          900: '#14532d',
        },
        surface: {
          900: '#0a0f0d',
          800: '#0f1712',
          700: '#162019',
          600: '#1e2e24',
          500: '#263d30',
        },
        // Stitch design system tokens
        primary: '#4edea3',
        'primary-container': '#10b981',
        'on-primary': '#003824',
        'on-primary-container': '#00422b',
        secondary: '#8bd6b6',
        'secondary-container': '#005c43',
        'on-secondary': '#003828',
        'on-secondary-container': '#87d2b2',
        background: '#0e1511',
        'background-main': '#0A0A0A',
        'on-background': '#dde4dd',
        'surface-dim': '#0e1511',
        'surface-bright': '#343b36',
        'surface-card': '#171717',
        'surface-elevated': '#262626',
        'surface-container-lowest': '#09100c',
        'surface-container-low': '#161d19',
        'surface-container': '#1a211d',
        'surface-container-high': '#242c27',
        'surface-container-highest': '#2f3632',
        'surface-variant': '#2f3632',
        'on-surface': '#dde4dd',
        'on-surface-variant': '#bbcabf',
        outline: '#86948a',
        'outline-variant': '#3c4a42',
        'accent-teal': '#14B8A6',
        'text-primary': '#FFFFFF',
        'text-secondary': '#A3A3A3',
        'status-positive': '#10B981',
        'status-warning': '#F59E0B',
        'status-negative': '#EF4444',
        'chart-yield': '#10B981',
        'chart-fees': '#F59E0B',
        'chart-il': '#EF4444',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
        manrope: ['Manrope', 'sans-serif'],
        'headline-xl': ['Manrope', 'sans-serif'],
        'headline-lg': ['Manrope', 'sans-serif'],
        'headline-md': ['Manrope', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'stat-value': ['Manrope', 'sans-serif'],
        'label-caps': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-xl': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-lg': ['32px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '1.4', fontWeight: '400' }],
        'stat-value': ['28px', { lineHeight: '1', fontWeight: '700' }],
        'label-caps': ['12px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '600' }],
      },
      spacing: {
        'stack-sm': '8px',
        'stack-md': '16px',
        'stack-lg': '32px',
        gutter: '24px',
        'section-gap': '80px',
        'margin-mobile': '16px',
      },
    },
  },
  plugins: [],
};

export default config;
